version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - volumes/mosquitto:/mosquitto/:rw
    ports:
      - 1883:1883 #mqtt
      - 9001:9001 #websocket
